AWSTemplateFormatVersion: "2010-09-09"
Description: "Create slack"
# ------------------------------------------------------------#
# Parameters
# ------------------------------------------------------------#
Parameters:
  PipelineName:
    Type: String
    Description: Target Pipeline Name
  ChatBotArn:
    Type: String
    Description: AWS ChatBot ARN
Resources:
# ------------------------------------------------------------#
# SNSRule
# ------------------------------------------------------------#
  PipelineNotificationRule:
    Type: AWS::CodeStarNotifications::NotificationRule
    Properties:
      Name: pipeline-notification-rule
      DetailType: FULL
      Resource: !Join [ '', [ 'arn:aws:codepipeline:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref PipelineName ] ]
      EventTypeIds:
        - codepipeline-pipeline-pipeline-execution-succeeded
        - codepipeline-pipeline-pipeline-execution-failed
        - codepipeline-pipeline-pipeline-execution-canceled
      Targets:
        -
          TargetType: AWSChatbotSlack
          TargetAddress: !Ref ChatBotArn